# Generated by Django 4.2.3 on 2023-07-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customerapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="district",
            name="wikipedia_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
